<div>
				<textarea id="testData" cols="100" rows="30">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hendrerit tincidunt nunc, at lobortis augue fringilla eget. Suspendisse vel tincidunt lorem. Sed facilisis aliquam nunc sit amet adipiscing. Quisque porttitor placerat est, ut aliquet tellus. Donec pharetra erat sed lacus porttitor, quis convallis eros congue. Curabitur sed mauris non massa vestibulum lacinia. Pellentesque id condimentum neque. Ut sit amet nunc nec nisl suscipit fringilla ut eget metus. Morbi sagittis quis neque egestas viverra. Nunc laoreet elit a mauris auctor fringilla. Donec mattis mi felis, quis egestas mi consectetur vitae. Integer mattis nibh sem, in imperdiet nulla gravida ut. Cras sed lacinia libero, faucibus tristique erat. Nam at mi placerat, condimentum elit et, molestie nulla. Curabitur iaculis mollis condimentum. Donec justo sem, euismod vel iaculis vel, fermentum et elit.

Phasellus pretium hendrerit dignissim. Pellentesque lacinia urna sed felis rhoncus, congue faucibus enim aliquet. Morbi vel ligula purus. Aliquam in enim vel dui imperdiet varius quis eu lacus. Donec fermentum bibendum purus vitae lobortis. Nullam at magna accumsan, vestibulum dolor id, imperdiet velit. Quisque blandit, felis eu lobortis suscipit, lorem purus condimentum turpis, id sagittis leo urna ut erat. Sed venenatis sed mi nec suscipit. Phasellus eleifend ipsum et volutpat ultrices. Duis scelerisque dapibus sollicitudin. Morbi ut dictum lectus. In rutrum dui venenatis, tristique purus in, facilisis enim. Aliquam luctus viverra varius. Nunc semper nisl nec aliquet faucibus.

Mauris venenatis nunc eros, nec commodo velit placerat fringilla. Vivamus mattis at dolor a imperdiet. In venenatis metus ut urna ornare, et pellentesque purus vestibulum. Nullam ultricies mauris venenatis aliquet gravida. Phasellus consectetur ultrices odio ut accumsan. Integer malesuada facilisis purus, sed luctus orci facilisis at. Vivamus luctus vehicula lacus sed eleifend. Aliquam imperdiet, augue at congue venenatis, nisi lacus viverra tellus, a lacinia massa nisl fringilla urna. Morbi consectetur erat eget mauris luctus, at bibendum odio consequat. Integer in pulvinar risus. Duis sapien risus, auctor et nisl et, ultrices vulputate ipsum.

Phasellus scelerisque orci neque, ut vehicula arcu euismod quis. Sed auctor, metus non volutpat cursus, ante erat facilisis odio, vel dictum augue nisi a diam. Nulla ac elementum ante, vel pretium nisi. Ut ipsum dolor, blandit id lacus ac, viverra tristique mauris. Nulla est mi, sagittis a magna pretium, gravida lobortis est. Proin a semper felis. In blandit risus non volutpat venenatis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris sit amet iaculis urna, sit amet tincidunt justo. Pellentesque pretium placerat enim non tempor. Nulla tincidunt fermentum interdum. Nulla nec aliquam velit, et tincidunt ante.

Duis blandit diam blandit pharetra pellentesque. Ut non rhoncus libero. Ut nec erat sed magna ornare adipiscing eget at odio. Suspendisse id egestas eros. Fusce id libero et sapien pretium gravida. Quisque mattis, felis sed pellentesque posuere, justo erat ultrices enim, id vestibulum metus dui in purus. Duis eu odio varius lorem volutpat dapibus nec ac magna. Sed fringilla tincidunt tellus ut pellentesque. Proin sit amet pharetra erat, quis viverra elit. Ut placerat volutpat nisl, in rutrum mi ultrices non.
				</textarea><br>
				<input type="button" value="Compress" onclick="document.getElementById('compressedData').value=LZW.compress(document.getElementById('testData').value);"><br>
				<textarea id="compressedData" cols="100" rows="30"></textarea>
			</div>